### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by nebulousal** [bohoffi/boss-gt-1000-patch-editor#17]
Basti-

I'm a guitarist and I dabble in dev as well. Would love to this working on my local machine (mac). Any advice for installing? To your knowledge is it still operational ?

**Comment by bohoffi** [comment]
@nebulousal Thanks for reaching out but I'm sorry for disappointing you. I've never found the time to pick up the project again to work on it

**Comment by nebulousal** [comment]
Sorry to hear that- but, does it work? Did you ever get it working when you first created it?

**Comment by bohoffi** [comment]
It's nothing more than the rough project structure
